Repository Sygic/sygic-maps-kit-android, pull requests merged in 2019-06, with the labels that each got.

#48 Bugfix - On map click listener
  app/samples/src/main/java/com/sygic/samples/browsemap/BrowseMapClickListenerActivity.kt
  build.gradle
  modules/browsemap/src/main/java/com/sygic/maps/module/browsemap/BrowseMapFragment.kt
  modules/browsemap/src/main/java/com/sygic/maps/module/browsemap/viewmodel/BrowseMapFragmentViewModel.kt
  modules/browsemap/src/test/java/com/sygic/modules/browsemap/BrowseMapFragmentViewModelTest.kt
  modules/common/src/main/java/com/sygic/maps/module/common/listener/OnMapClickListener.kt
  modules/common/src/main/java/com/sygic/maps/module/common/utils/Extensions.kt
  uikit/viewmodels/src/main/java/com/sygic/maps/uikit/viewmodels/common/extensions/SdkExtensions.kt
  uikit/viewmodels/src/main/java/com/sygic/maps/uikit/viewmodels/common/sdk/viewobject/SelectionType.java
Labels: bug

#59 Feature/ms 5798 vm initialization refactor
  app/samples/src/main/java/com/sygic/samples/search/SearchFromBrowseMapActivity.kt
  app/samples/src/main/java/com/sygic/samples/search/viewmodels/SearchFromBrowseMapActivityViewModel.kt
  modules/browsemap/src/main/java/com/sygic/maps/module/browsemap/BrowseMapFragment.kt
  modules/browsemap/src/main/java/com/sygic/maps/module/browsemap/extensions/BrowseMapExtensions.kt
  modules/browsemap/src/main/java/com/sygic/maps/module/browsemap/viewmodel/BrowseMapFragmentViewModel.kt
  modules/browsemap/src/test/java/com/sygic/modules/browsemap/BrowseMapFragmentViewModelTest.kt
  modules/common/src/main/java/com/sygic/maps/module/common/MapFragmentWrapper.kt
  modules/common/src/main/java/com/sygic/maps/module/common/component/MapFragmentInitComponent.kt
  modules/common/src/main/java/com/sygic/maps/module/common/component/MapFragmentInitConstants.kt
  modules/common/src/main/java/com/sygic/maps/module/common/listener/OnMapClickListener.kt
  modules/common/src/main/java/com/sygic/maps/module/common/provider/ModuleConnectionProvider.kt
  uikit/views/src/main/java/com/sygic/maps/uikit/views/common/extensions/BundleExtensions.kt
  uikit/views/src/main/java/com/sygic/maps/uikit/views/poidetail/PoiDetailBottomDialogFragment.kt
Labels: bug, enhancement

#63 Feature - Propagate engine initialization error to the user
  uikit/viewmodels/src/main/java/com/sygic/maps/uikit/viewmodels/common/initialization/InitializationState.java
  uikit/viewmodels/src/main/java/com/sygic/maps/uikit/viewmodels/common/initialization/SdkInitializationManager.kt
  uikit/viewmodels/src/main/java/com/sygic/maps/uikit/viewmodels/common/initialization/SdkInitializationManagerImpl.kt
Labels: enhancement

#54 Feature - Search error states (finalize)
  build.gradle
  modules/search/src/main/res/layout/layout_search.xml
  uikit/viewmodels/src/main/java/com/sygic/maps/uikit/viewmodels/common/utils/SdkUtils.kt
  uikit/viewmodels/src/main/java/com/sygic/maps/uikit/viewmodels/searchresultlist/SearchResultListViewModel.kt
  uikit/views/src/main/java/com/sygic/maps/uikit/views/searchresultlist/SearchResultList.kt
  uikit/views/src/main/java/com/sygic/maps/uikit/views/searchresultlist/SearchResultListErrorViewSwitcherIndex.java
  uikit/views/src/main/res/layout/layout_search_result_list_internal.xml
  uikit/views/src/main/res/values/strings.xml
Labels: enhancement

#58 Feature - Search styling
  build.gradle
  uikit/views/src/main/java/com/sygic/maps/uikit/views/searchresultlist/SearchResultList.kt
  uikit/views/src/main/java/com/sygic/maps/uikit/views/searchtoolbar/SearchToolbar.kt
  uikit/views/src/main/java/com/sygic/maps/uikit/views/searchtoolbar/SearchToolbarBindingAdapters.kt
  uikit/views/src/main/res/drawable/search_toolbar_background.xml
  uikit/views/src/main/res/layout/layout_search_item_result_internal.xml
  uikit/views/src/main/res/layout/layout_search_toolbar_internal.xml
  uikit/views/src/main/res/values/attrs.xml
  uikit/views/src/main/res/values/strings.xml
  uikit/views/src/main/res/values/styles.xml
Labels: enhancement

#60 Feature - Search wiki
  README.md
  app/samples/src/main/java/com/sygic/samples/app/viewmodels/SamplesActivityViewModel.kt
  app/samples/src/main/res/drawable/ic_search_result_list.xml
  app/samples/src/main/res/drawable/ic_search_toolbar.xml
  app/samples/src/main/res/menu/activity_main_drawer.xml
  app/samples/src/main/res/values/strings.xml
  assets/images/screenshots.png
  assets/images/screenshots_orig.png
  assets/images/uikit/search_result_list.png
  assets/images/uikit/search_toolbar.png
  assets/screencasts/S_0_def.gif
  assets/screencasts/S_1_from_BM.gif
  assets/screencasts/S_2_from_BM_pins.gif
  assets/screencasts/S_3_prefilled.gif
Labels: enhancement
